"""libtea - Python client library for the Transparency Exchange API (TEA)."""

from importlib.metadata import version

from libtea.client import TEA_SPEC_VERSION, TeaClient
from libtea.exceptions import (
    TeaAuthenticationError,
    TeaChecksumError,
    TeaConnectionError,
    TeaDiscoveryError,
    TeaError,
    TeaInsecureTransportWarning,
    TeaNotFoundError,
    TeaRequestError,
    TeaServerError,
    TeaValidationError,
)
from libtea.models import (
    Artifact,
    ArtifactFormat,
    ArtifactType,
    Checksum,
    ChecksumAlgorithm,
    Collection,
    CollectionBelongsTo,
    CollectionUpdateReason,
    CollectionUpdateReasonType,
    Component,
    ComponentRef,
    ComponentReleaseWithCollection,
    DiscoveryInfo,
    ErrorType,
    Identifier,
    IdentifierType,
    PaginatedProductReleaseResponse,
    PaginatedProductResponse,
    Product,
    ProductRelease,
    Release,
    ReleaseDistribution,
    TeaServerInfo,
)

__version__ = version("libtea")
__all__ = [
    "TEA_SPEC_VERSION",
    "TeaClient",
    "TeaError",
    "TeaAuthenticationError",
    "TeaChecksumError",
    "TeaConnectionError",
    "TeaDiscoveryError",
    "TeaInsecureTransportWarning",
    "TeaNotFoundError",
    "TeaRequestError",
    "TeaServerError",
    "TeaValidationError",
    "Artifact",
    "ArtifactFormat",
    "ArtifactType",
    "Checksum",
    "ChecksumAlgorithm",
    "Collection",
    "CollectionBelongsTo",
    "CollectionUpdateReason",
    "CollectionUpdateReasonType",
    "Component",
    "ComponentRef",
    "ComponentReleaseWithCollection",
    "DiscoveryInfo",
    "ErrorType",
    "Identifier",
    "IdentifierType",
    "PaginatedProductReleaseResponse",
    "PaginatedProductResponse",
    "Product",
    "ProductRelease",
    "Release",
    "ReleaseDistribution",
    "TeaServerInfo",
    "__version__",
]
